# Generated by Django 3.1.2 on 2021-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210624_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Just a random text and blog', max_length=255),
        ),
    ]
