# Generated by Django 3.1.2 on 2021-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
    ]
